---
driver:
  name: dokken
  chef_version: 15
  # needed if you are running systemd in docker
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken
  chef_license: accept
  # nodes_path: test/fixtures/nodes
  # roles_path: test/fixtures/roles
  # environments_path: test/fixtures/environments
  # client_rb:
  #   environment: kitchen

verifier:
  name: inspec

platforms:
  - name: ubuntu-1604
    named_run_list: debian
    driver:
      image: ubuntu:16.04
      privileged: true
      pid_one_command: /bin/systemd
      intermediate_instructions: # any tasks before runlist is evaluated and run
      - RUN apt-get -y update && apt-get install -y net-tools curl
      - ENV container docker
      - CMD ['/usr/sbin/init']
  - name: ubuntu-1804
    named_run_list: debian
    driver:
      image: dokken/ubuntu-18.04
      privileged: true
      pid_one_command: /bin/systemd
      intermediate_instructions: # any tasks before runlist is evaluated and run
      - RUN apt-get -y update && apt-get install -y net-tools curl
      - ENV container docker
      - CMD ['/usr/sbin/init']
      attributes:
      ports: '4141' # exposes port to be able to access atlantis UI in docker container
suites:
  - name: server
    run_list:
    - recipe[atlantis_test::server]
