sudo: required

service: docker

language: ruby
rvm:
  - 2.4.3

env:
  matrix:
    - INSTANCE=server-ubuntu-1404
    - INSTANCE=server-ubuntu-1604
    - INSTANCE=server-ubuntu-1804

# before_install:
# - openssl aes-256-cbc -K $encrypted_926c7e7ff18b_iv -iv $encrypted_926c7e7ff18b_iv -in .travis/majormoses.pem.enc -out .travis/majormoses.pem -d

before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )

install: bundle --jobs=3 --retry=3
cache:
  directories:
    - vendor/bundle

script:
  - INSTANCE=$INSTANCE make travis

  # TODO: create a bot user and encrypt that users creds instead
# deploy:
#   provider: chef-supermarket
#   user_id: majormoses-bot
#   client-key: .travis/majormoses-bot.pem
#   cookbook_category: Others
#   on:
#     tags: true
