addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

env:
  - CHEF_LICENSE="accept"

env:
  matrix:
    - INSTANCE=server-ubuntu-1604
    - INSTANCE=server-ubuntu-1804

# before_install:
# - openssl aes-256-cbc -K $encrypted_926c7e7ff18b_iv -iv $encrypted_926c7e7ff18b_iv -in .travis/majormoses.pem.enc -out .travis/majormoses.pem -d

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version
  
script: KITCHEN_LOCAL_YAML=.kitchen.yml kitchen verify ${INSTANCE}
